services:
  twitch-drops-miner: 
    image: theduke203/twitchminer:latest
    container_name: twitchminer
    restart: unless-stopped
    ports:
    # Change the port as you wish
      - "8085:8080"
    volumes:
      - ./data:/data
    environment:
      - TZ=UTC
      - DOCKER_CONTAINER=true
